### PR TITLE
Fix : Open source section bug

### PR DESCRIPTION
**Pull request by Meetjain1**
Fixed open source section bug in readme.md file see the changes in the screenshot above part is its current state and below part is its final part with animated emojis added and fixed the bugs.

readme

### CODE REVIEW

**Comment by 4darsh-Dev** [comment]
@Meetjain1 Images are stretched fix this issue.

**Comment by Meetjain1** [comment]
open

@4darsh-Dev done with the changes.

**Review by 4darsh-Dev — APPROVED** [review]
fine.

**Comment by 4darsh-Dev** [comment]
GSSoC 24 has been completed Finally'
 It was a great experience working with you all 
 Thanks💗 for your valuable contributions! 
 PA nomination has been started, Do fill out the forms soon. Share your experiences and let's connect on socials

**Pull request merged**
