### PR TITLE
#76: Hovering effects Made

### PR DESCRIPTION
**Pull request by aanchalpahuja18**
Hovering effects in nav section has been improved & footer's hovering effects on icons & links have been improved

### CODE REVIEW

**Comment by aanchalpahuja18** [comment]
@4darsh-Dev I have made the changes kindly review it once.

**Review by 4darsh-Dev — COMMENTED** [review]
much better now, 
good work @aanchalpahuja18 
just you need to wait because there is other contributor PR which needed to be merged for responsiveness so you have to sync and fork once it is merged to avoid any conflicts.

**Comment by aanchalpahuja18** [comment]
Thankyou for the appreciation @4darsh-Dev it means a lot. 
Will wait for that

**Comment by aanchalpahuja18** [comment]
Thankyou for the appreciation @4darsh-Dev it means a lot. 
Will wait for that

**Review by 4darsh-Dev — COMMENTED** [review]
sync and fork as the repo got new changes recently.

**Review by 4darsh-Dev — CHANGES_REQUESTED** [review]
see the vercel preview

**Pull request closed without merging**
