### PR TITLE
Added the feature of see faq answer on hover

### PR DESCRIPTION
**Pull request by Utsavladia**
## Demo Video

https://github.com/user-attachments/assets/d90863a1-593c-4768-b340-0f365e83245f

### CODE REVIEW

**Comment by 4darsh-Dev** [comment]
@Utsavladia add better animations and effects, on hover, 
it' looking quite basic.

**Comment by Utsavladia** [comment]
@4darsh-Dev 
Its same as before just the functionality is added

I can add if you want .. could you elaborate on what you need the hover effect

**Comment by 4darsh-Dev** [comment]
@Utsavladia  
- adjust the box-shadow property to a better look
- currently, faq section opens up by clicking button only, add this to the whole question container for a better user exp.
- make smoother transition

**Comment by Utsavladia** [comment]
@4darsh-Dev 
Fixed the trnasition to smooth and shadow to whole question-answer


https://github.com/user-attachments/assets/cdbc5410-9217-470f-9e82-bc6fcce496b0

**Review by 4darsh-Dev — APPROVED** [review]
ok 👍🏻

**Comment by 4darsh-Dev** [comment]
GSSoC 24 has been completed Finally'
 It was a great experience working with you all 
 Thanks💗 for your valuable contributions! 
 PA nomination has been started, Do fill out the forms soon. Share your experiences and let's connect on socials

**Pull request merged**
