### PR TITLE
enhancement of home page

### PR DESCRIPTION
**Pull request by Aashka19**
issue #77 solved
plz review and merge

### CODE REVIEW

**Review by 4darsh-Dev — CHANGES_REQUESTED** [review]
@Aashka19  share the SS of your change. 
sync and fork as the repo got new changes recently.

**Comment by Aashka19** [comment]
ohk sir

**Comment by Aashka19** [comment]
should i close this pull request?

**Comment by Aashka19** [comment]
sir i moved this picture to right 
this was the enhancement issue and it is getting reflecting on the site as well

Screenshot 2024-06-16 at 10 12 59 PM

**Comment by 4darsh-Dev** [comment]
@Aashka19 you've made changes in wrong directory, 
django-web-app is the one where you've to make changes.

**Comment by Aashka19** [comment]
ohk i'll close this one and open a new pull request

**Pull request closed without merging**
