### PR TITLE
updated navbar responsive , welcome page responsive #84

### PR DESCRIPTION
**Pull request by anurag6569201**
created responsive navbar for mobile tab and pc version 
created welcome page responsiveness for welcome page 
shifted 2nd section to the 3rd position
create responsive.css for footer navbar and welcome page code

image
image
image

### CODE REVIEW

**Review by 4darsh-Dev — CHANGES_REQUESTED** [review]
## Changes required on mobile display
1. improper image size 
Screenshot 2024-06-15 001114

2. Less padding/margin overall space b/w sections
see preview of deployment on your mobile phone display

3. apply font family in nav-items and increase spacing b/w items

## changes on i pad display
1. improper image size and navbar
Screenshot 2024-06-15 002044

## changes on pc display
1. improper spacing b/w section ( add margin and padding )
Screenshot 2024-06-15 002242

**Review by 4darsh-Dev — CHANGES_REQUESTED** [review]
Do check preview to avoid issue and add necessary media query breakpoints.

**Comment by anurag6569201** [comment]
> Do check preview to avoid issue and add necessary media query breakpoints.

ok i will do it ASAP

**Comment by 4darsh-Dev** [comment]
@anurag6569201  now you can see the preview.

**Review by 4darsh-Dev — APPROVED** [review]
some minor changes are required, 
i'll fix them.

**Pull request merged**
