### PR TITLE
issue number #77 and #78 resolved

### PR DESCRIPTION
**Pull request by Aashka19**

### CODE REVIEW

**Review by 4darsh-Dev — CHANGES_REQUESTED** [review]
@Aashka19  everything seems fine, 
just revert the commits in django-mlapi-backend as they are not required and might cause some issues

**Comment by Aashka19** [comment]
the issues should be in djanjo-mlapi-backend or djanjo-mlapi-app?

**Comment by Aashka19** [comment]
this pull request is for django-mlapi-app and there is no changes in djanjo-mlapi-backend

**Comment by 4darsh-Dev** [comment]
## see the changes section
Screenshot 2024-06-21 111216

**Comment by Aashka19** [comment]
done

**Comment by 4darsh-Dev** [comment]
This won't make any difference, @Aashka19 
See the preview

**Comment by Aashka19** [comment]
i did the changes in djanjo-mlapi-app and reverted the changes from backend

**Comment by Aashka19** [comment]
in my repo the changes are good to go and are in django-mlapi-app and not in djanjo-mlapi-backend and in main repo there are no changes 

i've changed the layout and hover button as told
plz accept the pr
Screenshot 2024-06-24 at 5 32 37 PM
Screenshot 2024-06-24 at 5 33 00 PM


these above 2 are my changes in django-mlapi-app and below two are the main repo code


Screenshot 2024-06-24 at 5 33 45 PM

 
Screenshot 2024-06-24 at 5 34 06 PM

**Comment by Aashka19** [comment]
do i get any points for this issue?
as on main website one of my changes are there,
could you plz give me points for gssoc label and solving atleast one issue?

**Pull request closed without merging**
