### PR TITLE
feat: Modify Home Page

### PR DESCRIPTION
**Pull request by AshmitaBarthwal**
I added Modification to the Home-Page of the website-----

1) Enhanced the navbar section to align it with website's blue theme.
2) In the main home page i added effects to the logo of the website(on taking the cursor to the logo it will pop up a lil).
3) Changed the appearance of the text in text area
4) Created a dynamic glass box effect using CSS properties (you can see the box moving while visiting the website).
5) Made changes to the buttons to make them more attractive.

ISSUE NO.: #149
TITLE: Modifying The Home Page

ADDING THE SCREENSHOTS:

BEFORE :
Screenshot 2024-07-18 162842

AFTER:
Screenshot 2024-07-18 161904

Priority: High

I am a part of Gssoc 24.

### CODE REVIEW

**Comment by AshmitaBarthwal** [comment]
@4darsh-Dev Please review my pull request.

**Comment by AshmitaBarthwal** [comment]
@4darsh-Dev please mark the LEVEL OF CONTRIBUTION label under GSSOC 24.

**Review by 4darsh-Dev — CHANGES_REQUESTED** [review]
@AshmitaBarthwal 
## Nice, Few changes are required
1. In the box apply translate Y to move CogniGuard text in parallel with logo
2. Change Dark Pattern text color to black 
3. For menu items color use color palette or colors from CSS vars. 

**Make sure it is responsive on mobile dispaly**

**Comment by AshmitaBarthwal** [comment]
@4darsh-Dev Made the changes you said. Review it once.

Screenshot 2024-07-18 180040

**Review by 4darsh-Dev — APPROVED** [review]
nice work

**Comment by AshmitaBarthwal** [comment]
thank you @4darsh-Dev

**Comment by 4darsh-Dev** [comment]
GSSoC 24 has been completed Finally'
 It was a great experience working with you all 
 Thanks💗 for your valuable contributions! 
 PA nomination has been started, Do fill out the forms soon. Share your experiences and let's connect on socials

**Pull request merged**
